### ISSUE TITLE
Import Broken 

### ISSUE THREAD

**Issue by ralvarado7** [nilshoenson/shared-text-styles#54] opened 2018-05-14 14:33 UTC
Nothing happens after I import. 
Sketch 50 
Shared Text Styles 1.6.3

**Comment by vitorfernandes** [comment] 2018-05-14 20:44
any workaround?

**Comment by vu-j** [comment] 2018-05-14 21:08
Yeah, broken on Sketch 50 using v. 1.6.3 on my end as well. Looking forward to a fix!

**Comment by nilshoenson** [comment] 2018-05-14 22:34
Thanks for reporting. Closing this as it's a duplicate of #52.

**Closed by nilshoenson** 2018-05-14 22:34 UTC
