### ISSUE TITLE
Import feature not working in Sketch 50

### ISSUE THREAD

**Issue by Viditgupta5151** [nilshoenson/shared-text-styles#53] opened 2018-05-14 10:55 UTC
<img width="1280" alt="screen shot 2018-05-14 at 6 55 24 pm" src="https://user-images.githubusercontent.com/39264121/39993409-566723d0-57a8-11e8-8fc4-420f7ccd7fe7.png">

**Comment by nilshoenson** [comment] 2018-05-14 22:33
Thanks for reporting. Closing this as it's a duplicate of #52

**Closed by nilshoenson** 2018-05-14 22:33 UTC
